import { Database } from "@/integrations/supabase/types";

type RegimeTributario = Database["public"]["Enums"]["regime_tributario"];
type DepartamentoTipo = Database["public"]["Enums"]["departamento_tipo"];

type PeriodicidadeTipo = "mensal" | "trimestral" | "semestral" | "anual";

interface SuggestedTask {
  titulo: string;
  descricao: string;
  departamento: DepartamentoTipo;
  prioridade: string;
  dia_vencimento?: number;
  prazo_dias?: number;
  requer_anexo?: boolean;
  periodicidade: PeriodicidadeTipo;
  regimes: RegimeTributario[];
}

export const SUGGESTED_TASKS: SuggestedTask[] = [
  // ===================== MEI =====================
  {
    titulo: "DAS-MEI",
    descricao: "Pagamento do Documento de Arrecadação do Simples Nacional do MEI (INSS + ICMS/ISS)",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 20,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["mei"],
  },
  {
    titulo: "DASN-SIMEI",
    descricao: "Declaração Anual do Simples Nacional para o MEI - prazo até 31/05",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 15,
    periodicidade: "anual",
    regimes: ["mei"],
  },
  {
    titulo: "Relatório Mensal de Receitas Brutas",
    descricao: "Preenchimento do relatório mensal de receitas brutas do MEI",
    departamento: "fiscal",
    prioridade: "media",
    dia_vencimento: 20,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["mei"],
  },

  // ===================== SIMPLES NACIONAL =====================
  {
    titulo: "PGDAS-D",
    descricao: "Programa Gerador do Documento de Arrecadação do Simples Nacional - Declaratório",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 20,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["simples_nacional"],
  },
  {
    titulo: "DAS - Simples Nacional",
    descricao: "Emissão e pagamento do DAS mensal do Simples Nacional",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 20,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["simples_nacional"],
  },
  {
    titulo: "DEFIS",
    descricao: "Declaração de Informações Socioeconômicas e Fiscais - prazo até 28/03",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 15,
    periodicidade: "anual",
    regimes: ["simples_nacional"],
  },
  {
    titulo: "DESTDA",
    descricao: "Declaração de Substituição Tributária, Diferencial de Alíquota e Antecipação",
    departamento: "fiscal",
    prioridade: "media",
    dia_vencimento: 28,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["simples_nacional"],
  },
  {
    titulo: "DIRF",
    descricao: "Declaração do Imposto sobre a Renda Retido na Fonte",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 15,
    periodicidade: "anual",
    regimes: ["simples_nacional", "lucro_presumido", "lucro_real"],
  },
  {
    titulo: "RAIS",
    descricao: "Relação Anual de Informações Sociais",
    departamento: "departamento_pessoal",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 10,
    periodicidade: "anual",
    regimes: ["simples_nacional", "lucro_presumido", "lucro_real"],
  },
  {
    titulo: "eSocial - Eventos Periódicos",
    descricao: "Envio de eventos periódicos do eSocial (folha de pagamento, remuneração)",
    departamento: "departamento_pessoal",
    prioridade: "alta",
    dia_vencimento: 15,
    prazo_dias: 3,
    periodicidade: "mensal",
    regimes: ["simples_nacional", "lucro_presumido", "lucro_real"],
  },
  {
    titulo: "DCTFWeb",
    descricao: "Declaração de Débitos e Créditos Tributários Federais Previdenciários e de Outras Entidades",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 15,
    prazo_dias: 3,
    periodicidade: "mensal",
    regimes: ["simples_nacional", "lucro_presumido", "lucro_real"],
  },
  {
    titulo: "FGTS Digital (GRFGTS)",
    descricao: "Recolhimento do FGTS via FGTS Digital",
    departamento: "departamento_pessoal",
    prioridade: "alta",
    dia_vencimento: 20,
    prazo_dias: 3,
    periodicidade: "mensal",
    regimes: ["simples_nacional", "lucro_presumido", "lucro_real"],
  },
  {
    titulo: "Folha de Pagamento",
    descricao: "Processamento e cálculo da folha de pagamento mensal",
    departamento: "departamento_pessoal",
    prioridade: "alta",
    dia_vencimento: 5,
    prazo_dias: 3,
    periodicidade: "mensal",
    regimes: ["simples_nacional", "lucro_presumido", "lucro_real"],
  },

  // ===================== LUCRO PRESUMIDO =====================
  {
    titulo: "DCTF Mensal",
    descricao: "Declaração de Débitos e Créditos Tributários Federais",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 15,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["lucro_presumido", "lucro_real"],
  },
  {
    titulo: "EFD-Contribuições (PIS/COFINS)",
    descricao: "Escrituração Fiscal Digital das Contribuições incidentes sobre a Receita",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 15,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["lucro_presumido", "lucro_real"],
  },
  {
    titulo: "EFD-ICMS/IPI (SPED Fiscal)",
    descricao: "Escrituração Fiscal Digital de ICMS e IPI",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 15,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["lucro_presumido", "lucro_real"],
  },
  {
    titulo: "IRPJ - Apuração Trimestral",
    descricao: "Apuração do Imposto de Renda Pessoa Jurídica - trimestral",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 10,
    periodicidade: "trimestral",
    regimes: ["lucro_presumido"],
  },
  {
    titulo: "CSLL - Apuração Trimestral",
    descricao: "Apuração da Contribuição Social sobre o Lucro Líquido - trimestral",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 10,
    periodicidade: "trimestral",
    regimes: ["lucro_presumido"],
  },
  {
    titulo: "PIS/COFINS - Apuração",
    descricao: "Apuração e recolhimento de PIS e COFINS (cumulativo ou não-cumulativo)",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 25,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["lucro_presumido", "lucro_real"],
  },
  {
    titulo: "ECF",
    descricao: "Escrituração Contábil Fiscal - prazo até último dia útil de julho",
    departamento: "contabil",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 20,
    periodicidade: "anual",
    regimes: ["lucro_presumido", "lucro_real"],
  },
  {
    titulo: "ECD (SPED Contábil)",
    descricao: "Escrituração Contábil Digital - prazo até último dia útil de maio",
    departamento: "contabil",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 20,
    periodicidade: "anual",
    regimes: ["lucro_presumido", "lucro_real"],
  },
  {
    titulo: "GIA (Guia de Informação e Apuração do ICMS)",
    descricao: "Guia de Informação e Apuração do ICMS estadual",
    departamento: "fiscal",
    prioridade: "media",
    dia_vencimento: 15,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["lucro_presumido", "lucro_real"],
  },
  {
    titulo: "ISS - Declaração e Recolhimento",
    descricao: "Declaração e recolhimento do Imposto Sobre Serviços municipal",
    departamento: "fiscal",
    prioridade: "media",
    dia_vencimento: 10,
    prazo_dias: 3,
    periodicidade: "mensal",
    regimes: ["lucro_presumido", "lucro_real"],
  },
  {
    titulo: "Balancete Mensal",
    descricao: "Elaboração do balancete de verificação mensal",
    departamento: "contabil",
    prioridade: "media",
    dia_vencimento: 20,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["lucro_presumido", "lucro_real"],
  },
  {
    titulo: "Conciliação Bancária",
    descricao: "Conciliação dos extratos bancários com a contabilidade",
    departamento: "contabil",
    prioridade: "media",
    dia_vencimento: 15,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["lucro_presumido", "lucro_real"],
  },

  // ===================== LUCRO REAL (exclusivas) =====================
  {
    titulo: "IRPJ - Apuração Trimestral/Anual",
    descricao: "Apuração do IRPJ por estimativa mensal ou trimestral - Lucro Real",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 10,
    periodicidade: "trimestral",
    regimes: ["lucro_real"],
  },
  {
    titulo: "CSLL - Apuração Lucro Real",
    descricao: "Apuração da CSLL sobre o lucro real - trimestral ou anual",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 10,
    periodicidade: "trimestral",
    regimes: ["lucro_real"],
  },
  {
    titulo: "Lalur/Lacs",
    descricao: "Livro de Apuração do Lucro Real / Livro de Apuração da CSLL",
    departamento: "contabil",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 15,
    periodicidade: "trimestral",
    regimes: ["lucro_real"],
  },
  {
    titulo: "EFD-Reinf",
    descricao: "Escrituração Fiscal Digital de Retenções e Outras Informações Fiscais",
    departamento: "fiscal",
    prioridade: "alta",
    dia_vencimento: 15,
    prazo_dias: 3,
    periodicidade: "mensal",
    regimes: ["lucro_presumido", "lucro_real"],
  },
  {
    titulo: "CIAP - Controle de Crédito de ICMS do Ativo Permanente",
    descricao: "Controle de Crédito de ICMS do Ativo Permanente - obrigatório para Lucro Real",
    departamento: "fiscal",
    prioridade: "media",
    dia_vencimento: 15,
    prazo_dias: 5,
    periodicidade: "mensal",
    regimes: ["lucro_real"],
  },
  {
    titulo: "Demonstrações Financeiras",
    descricao: "Elaboração do Balanço Patrimonial, DRE, DMPL, DFC e Notas Explicativas",
    departamento: "contabil",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 20,
    periodicidade: "anual",
    regimes: ["lucro_real"],
  },
  {
    titulo: "13º Salário - 1ª Parcela",
    descricao: "Cálculo e pagamento da primeira parcela do 13º salário (até 30/11)",
    departamento: "departamento_pessoal",
    prioridade: "alta",
    dia_vencimento: 28,
    prazo_dias: 10,
    periodicidade: "anual",
    regimes: ["simples_nacional", "lucro_presumido", "lucro_real"],
  },
  {
    titulo: "13º Salário - 2ª Parcela",
    descricao: "Cálculo e pagamento da segunda parcela do 13º salário (até 20/12)",
    departamento: "departamento_pessoal",
    prioridade: "alta",
    dia_vencimento: 20,
    prazo_dias: 5,
    periodicidade: "anual",
    regimes: ["simples_nacional", "lucro_presumido", "lucro_real"],
  },
  {
    titulo: "Férias - Controle e Pagamento",
    descricao: "Controle do período aquisitivo e concessivo de férias dos funcionários",
    departamento: "departamento_pessoal",
    prioridade: "media",
    prazo_dias: 30,
    periodicidade: "mensal",
    regimes: ["simples_nacional", "lucro_presumido", "lucro_real"],
  },
  {
    titulo: "CAGED / Novo CAGED (eSocial)",
    descricao: "Cadastro Geral de Empregados e Desempregados - via eSocial",
    departamento: "departamento_pessoal",
    prioridade: "alta",
    dia_vencimento: 7,
    prazo_dias: 2,
    periodicidade: "mensal",
    regimes: ["simples_nacional", "lucro_presumido", "lucro_real"],
  },
  {
    titulo: "SEFIP/GFIP",
    descricao: "Guia de Recolhimento do FGTS e Informações à Previdência Social",
    departamento: "departamento_pessoal",
    prioridade: "alta",
    dia_vencimento: 7,
    prazo_dias: 2,
    periodicidade: "mensal",
    regimes: ["simples_nacional", "lucro_presumido", "lucro_real"],
  },
];
